blank_issues_enabled: false
contact_links:
  - name: 💬 Sorular ve öneriler
    url: https://github.com/ArdaEkiz0/e-kesinti-otomasyon/discussions
    about: Soru sormak veya fikir paylaşmak için Discussions'ı kullanın